export const roleSeedData = [
  { name: 'CEO/Chair of Board', description: 'Chief Executive Officer' },
  { name: 'COO/VP Operations', description: 'Chief Operating Officer' },
  { name: 'COO/VP Finance', description: 'Chief Financial Officer' },
];

export const employeeSeedData = [
  { firstName: 'Zoë', lastName: 'Robins', roleName: 'Administration' },
  { firstName: 'Madeleine', lastName: 'Madden', roleName: 'Administration' },
  { firstName: 'Josha', lastName: 'Sadowski', roleName: 'Audit' },
  { firstName: 'Kate', lastName: 'Fleetwood', roleName: 'Audit' },
  { firstName: 'Priyanka', lastName: 'Bose', roleName: 'Banking Operations' },
  { firstName: 'Hammed', lastName: 'Animashuan', roleName: 'Banking Operations' },
  { firstName: 'Álvaro', lastName: 'Morte', roleName: 'Banking Operations' },
  { firstName: 'Taylor', lastName: 'Napier', roleName: 'Banking Operations' },
  { firstName: 'Alan', lastName: 'Simmonds', roleName: 'Banking Operations' },
  { firstName: 'Gil', lastName: 'Cardinal', roleName: 'Communications' },
  { firstName: 'Richard J.', lastName: 'Lewis', roleName: 'Communications' },
  { firstName: 'Randy', lastName: 'Bradshaw', roleName: 'Corporate Services' },
  { firstName: 'Tracey', lastName: 'Cook', roleName: 'Corporate Services' },
  { firstName: 'Lubomir', lastName: 'Mykytiuk', roleName: 'Corporate Services' },
  { firstName: 'Dakota', lastName: 'House', roleName: 'Facilities' },
  { firstName: 'Lori Lea', lastName: 'Okemah', roleName: 'Facilities' },
  { firstName: 'Renae', lastName: 'Morrisseau', roleName: 'Facilities' },
  { firstName: 'Rick', lastName: 'Belcourt', roleName: 'Facilities' },
  { firstName: 'Selina', lastName: 'Hanusa', roleName: 'Financial Services' },
  { firstName: 'Buffy', lastName: 'Gaudry', roleName: 'Financial Services' },
  { firstName: 'Shaneen Ann', lastName: 'Fox', roleName: 'Financial Services' },
  { firstName: 'Allan', lastName: 'Little', roleName: 'Financial Services' },
  { firstName: 'Danny', lastName: 'Rabbit', roleName: 'Financial Services' },
  { firstName: 'Jesse Ed', lastName: 'Azure', roleName: 'Human Resources' },
  { firstName: 'Stacy', lastName: 'Da Silva', roleName: 'Human Resources' },
  { firstName: 'Vladimír', lastName: 'Valenta', roleName: 'Human Resources' },
  { firstName: 'Samone', lastName: 'Sayeses-Whitney', roleName: 'Human Resources' },
  { firstName: 'Paul', lastName: 'Coeur', roleName: 'Human Resources' },
  { firstName: 'Graham', lastName: 'Greene', roleName: 'Information Technology' },
  { firstName: 'Sandika', lastName: 'Evergreen', roleName: 'Information Technology' },
  { firstName: 'Jennifer', lastName: 'Rodriguez', roleName: 'Information Technology' },
  { firstName: 'Aiyana', lastName: 'Littlebear', roleName: 'IT Technician' },
  { firstName: 'Inara', lastName: 'Thunderbird', roleName: 'IT Technician' },
  { firstName: 'Kaya', lastName: 'Runningbrook', roleName: 'IT Technician' },
  { firstName: 'Elara', lastName: 'Firehawk', roleName: 'IT Technician' },
  { firstName: 'Siona', lastName: 'Moonflower', roleName: 'IT Technician' },
  { firstName: 'Kaiyu', lastName: 'Greywolf', roleName: 'IT Technician' },
  { firstName: 'Ayawamat', lastName: 'Nightwind', roleName: 'IT Technician' },
  { firstName: 'Tala', lastName: 'Braveheart', roleName: 'IT Technician' },
  { firstName: 'Iniko', lastName: 'Stonebear', roleName: 'IT Technician' },
  { firstName: 'Onatah', lastName: 'Redhawk', roleName: 'IT Technician' },
  
];